name: Instagram Fetch Top Once

on:
  workflow_dispatch:

jobs:
  fetch_and_upload:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install gspread google-api-python-client pytz oauth2client

    - name: Run Instagram fetch script (once)
      env:
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        INSTAGRAM_BUSINESS_ID: '17841413261363491'
        HASHTAG: '華蔵寺庭園'
        SPREADSHEET_NAME: 'InstaContestLogTopMedia'
        GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS_JSON }}
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      run: |
        echo "$GOOGLE_CREDENTIALS" > client_secret.json
        python fetch_instagram_once.py
